export type ProviderAuthKind = "forward" | "oauth" | "key" | "local";

export interface ProviderCatalogEntry {
  readonly id: string;
  readonly label: string;
  readonly authKind: ProviderAuthKind;
  readonly adapter: string;
  readonly baseUrl: string;
  readonly defaultModel?: string;
  readonly models: readonly string[];
  readonly keyOptional?: boolean;
  readonly staticHeaders?: Readonly<Record<string, string>>;
  /** Explicit experimental status for local/dedicated additions not in the reference registry. */
  readonly experimental?: boolean;
}

export type ProviderPreset = ProviderCatalogEntry;
export type ProviderCatalogRow = ProviderCatalogEntry;

/**
 * 83 production provider entries synced from OpenCodex registry,
 * plus declared local experimental additions (devin).
 */
export const PROVIDER_CATALOG: readonly ProviderCatalogEntry[] = [
  {
    id: "openai",
    label: "OpenAI (Codex login)",
    authKind: "forward",
    adapter: "openai-responses",
    baseUrl: "https://chatgpt.com/backend-api/codex",
    models: [],
  },
  {
    id: "cursor",
    label: "Cursor (experimental)",
    authKind: "oauth",
    adapter: "cursor",
    baseUrl: "https://api2.cursor.sh",
    defaultModel: "auto",
    models: [
      "auto",
      "auto-balance",
      "auto-cost",
      "auto-intelligence",
      "claude-4-sonnet",
      "claude-4-sonnet-1m",
      "claude-4-sonnet-thinking",
      "claude-4.5-haiku",
      "claude-4.5-opus",
      "claude-4.5-opus-thinking",
      "claude-4.5-sonnet",
      "claude-4.5-sonnet-thinking",
      "claude-4.6-opus",
      "claude-4.6-opus-thinking",
      "claude-4.6-sonnet",
      "claude-4.6-sonnet-thinking",
      "claude-fable-5",
      "claude-fable-5-thinking",
      "claude-opus-4-7",
      "claude-opus-4-7-fast",
      "claude-opus-4-7-thinking",
      "claude-opus-4-7-thinking-fast",
      "claude-opus-4-8",
      "claude-opus-4-8-fast",
      "claude-opus-4-8-thinking",
      "claude-opus-4-8-thinking-fast",
      "claude-opus-5-fast",
      "claude-opus-5-thinking",
      "claude-opus-5-thinking-fast",
      "claude-sonnet-5",
      "claude-sonnet-5-thinking",
      "composer-1",
      "composer-2.5",
      "composer-2.5-fast",
      "gemini-2.5-flash",
      "gemini-3-flash",
      "gemini-3-pro",
      "gemini-3-pro-image-preview",
      "gemini-3.1-pro",
      "gemini-3.5-flash",
      "gemini-3.6-flash",
      "gemini-3.7-flash",
      "glm-5.2",
      "glm-5.3",
      "gpt-5-codex",
      "gpt-5-fast",
      "gpt-5-mini",
      "gpt-5.1",
      "gpt-5.1-codex",
      "gpt-5.1-codex-max",
      "gpt-5.1-codex-mini",
      "gpt-5.2",
      "gpt-5.2-codex",
      "gpt-5.3-codex",
      "gpt-5.4",
      "gpt-5.4-mini",
      "gpt-5.4-nano",
      "gpt-5.5",
      "gpt-5.5-extra",
      "gpt-5.6-luna",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "grok-4.5",
      "grok-4.5-fast",
      "grok-4.6",
      "grok-4.6-fast",
      "kimi-k2.7-code",
      "kimi-k3",
      "kimi-k3-1m",
    ],
  },
  {
    id: "xai",
    label: "xAI Grok",
    authKind: "oauth",
    adapter: "openai-chat",
    baseUrl: "https://api.x.ai/v1",
    defaultModel: "grok-4.5",
    models: [
      "grok-4.6",
      "grok-4.5",
      "grok-4.3",
      "grok-4.20-0309-reasoning",
      "grok-4.20-0309-non-reasoning",
      "grok-build-0.1",
      "grok-composer-2.5-fast",
    ],
  },
  {
    id: "command-code",
    label: "Command Code",
    authKind: "oauth",
    adapter: "command-code",
    baseUrl: "https://api.commandcode.ai",
    defaultModel: "deepseek/deepseek-v4-flash",
    models: [],
  },
  {
    id: "anthropic",
    label: "Anthropic Claude",
    authKind: "oauth",
    adapter: "anthropic",
    baseUrl: "https://api.anthropic.com",
    defaultModel: "claude-sonnet-5",
    models: [
      "claude-fable-5",
      "claude-sonnet-5",
      "claude-opus-5",
      "claude-opus-4-8",
      "claude-opus-4-7",
      "claude-opus-4-6",
      "claude-sonnet-4-6",
      "claude-haiku-4-5",
    ],
  },
  {
    id: "anthropic-apikey",
    label: "Anthropic (API key)",
    authKind: "key",
    adapter: "anthropic",
    baseUrl: "https://api.anthropic.com",
    defaultModel: "claude-sonnet-5",
    models: [
      "claude-fable-5",
      "claude-sonnet-5",
      "claude-opus-5",
      "claude-opus-4-8",
      "claude-opus-4-7",
      "claude-opus-4-6",
      "claude-sonnet-4-6",
      "claude-haiku-4-5",
    ],
  },
  {
    id: "kimi",
    label: "Kimi",
    authKind: "oauth",
    adapter: "openai-chat",
    baseUrl: "https://api.kimi.com/coding/v1",
    defaultModel: "kimi-k2.7-code",
    models: [
      "k3",
      "k3[1m]",
      "kimi-k2.7-code",
      "kimi-k2.7-code-highspeed",
      "kimi-k2.6",
      "kimi-k2.5",
      "kimi-for-coding",
    ],
  },
  {
    id: "kiro",
    label: "Kiro (AWS CodeWhisperer)",
    authKind: "key",
    adapter: "kiro",
    baseUrl: "https://runtime.us-east-1.kiro.dev",
    defaultModel: "kiro-auto",
    models: [
      "kiro-auto",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "gpt-5.6-luna",
      "claude-sonnet-5",
      "claude-opus-5",
      "claude-opus-4.8",
      "claude-opus-4.7",
      "claude-opus-4.6",
      "claude-opus-4.5",
      "claude-sonnet-4.6",
      "claude-sonnet-4.5",
      "claude-sonnet-4.0",
      "claude-haiku-4.5",
      "deepseek-3.2",
      "minimax-m2.5",
      "minimax-m2.1",
      "glm-5",
      "qwen3-coder-next",
    ],
  },
  {
    id: "nous",
    label: "Nous Portal",
    authKind: "oauth",
    adapter: "openai-chat",
    baseUrl: "https://inference-api.nousresearch.com/v1",
    defaultModel: "tencent/hy3:free",
    models: [
      "tencent/hy3:free",
      "poolside/laguna-s-2.1:free",
      "stepfun/step-3.7-flash:free",
      "poolside/laguna-xs-2.1:free",
    ],
  },
  {
    id: "openai-apikey",
    label: "OpenAI API",
    authKind: "key",
    adapter: "openai-responses",
    baseUrl: "https://api.openai.com/v1",
    defaultModel: "gpt-5.5",
    models: [
      "gpt-5.5",
      "gpt-5.6",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
      "gpt-5.6-luna",
      "gpt-5.6-sol-pro",
      "gpt-5.6-terra-pro",
      "gpt-5.6-luna-pro",
      "daybreak-red-latest",
      "daybreak-blue-latest",
    ],
  },
  {
    id: "umans",
    label: "Umans AI Coding Plan",
    authKind: "key",
    adapter: "anthropic",
    baseUrl: "https://api.code.umans.ai",
    defaultModel: "umans-coder",
    models: [
      "umans-coder",
      "umans-kimi-k2.7",
      "umans-flash",
      "umans-glm-5.3",
      "umans-glm-5.3-flash",
      "umans-glm-5.2",
      "umans-glm-5.1",
      "umans-qwen3.6-35b-a3b",
    ],
  },
  {
    id: "opencode-go",
    label: "opencode go",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://opencode.ai/zen/go/v1",
    defaultModel: "kimi-k2.7-code",
    models: [],
  },
  {
    id: "neuralwatt",
    label: "Neuralwatt Cloud",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.neuralwatt.com/v1",
    defaultModel: "glm-5.3",
    models: [
      "glm-5.3",
      "glm-5.3-fast",
      "glm-5.3-short",
      "glm-5.3-short-fast",
      "glm-5.3-flash",
      "glm-5.2",
      "glm-5.2-fast",
      "glm-5.2-short",
      "glm-5.2-short-fast",
      "kimi-k2.6",
      "kimi-k2.6-fast",
      "kimi-k2.7-code",
      "qwen3.5-397b",
      "qwen3.5-397b-fast",
      "qwen3.6-35b",
      "qwen3.6-35b-fast",
    ],
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://openrouter.ai/api/v1",
    models: [
      "anthropic/claude-sonnet-5",
      "openai/gpt-5.6",
      "openai/gpt-5.6-sol",
      "openai/gpt-5.6-terra",
      "openai/gpt-5.6-luna",
    ],
  },
  {
    id: "cline-pass",
    label: "ClinePass",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.cline.bot/api/v1",
    defaultModel: "cline-pass/kimi-k3",
    models: [
      "cline-pass/glm-5.3",
      "cline-pass/glm-5.3-flash",
      "cline-pass/glm-5.2",
      "cline-pass/kimi-k3",
      "cline-pass/kimi-k2.7-code",
      "cline-pass/kimi-k2.6",
      "cline-pass/deepseek-v4-pro",
      "cline-pass/deepseek-v4-flash",
      "cline-pass/mimo-v2.5",
      "cline-pass/mimo-v2.5-pro",
      "cline-pass/minimax-m3",
      "cline-pass/qwen3.8-max",
      "cline-pass/qwen3.7-max",
      "cline-pass/qwen3.7-plus",
    ],
  },
  {
    id: "cline",
    label: "Cline",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.cline.bot/api/v1",
    defaultModel: "anthropic/claude-sonnet-4-6",
    models: [
      "anthropic/claude-sonnet-4-6",
      "openai/gpt-4o",
      "google/gemini-2.5-pro",
      "deepseek/deepseek-chat",
      "minimax/minimax-m2.5",
    ],
  },
  {
    id: "orcarouter",
    label: "OrcaRouter",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.orcarouter.ai/v1",
    defaultModel: "openai/gpt-5.5",
    models: [
      "openai/gpt-5.5",
      "anthropic/claude-opus-4.8",
      "google/gemini-3.5-flash",
      "deepseek/deepseek-v4-pro",
      "orcarouter/auto",
    ],
  },
  {
    id: "bizrouter",
    label: "BizRouter",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.bizrouter.ai/v1",
    defaultModel: "openai/gpt-5.6-sol",
    models: ["openai/gpt-5.6-sol", "anthropic/claude-sonnet-5", "google/gemini-3.5-flash"],
  },
  {
    id: "groq",
    label: "Groq",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.groq.com/openai/v1",
    models: [],
  },
  {
    id: "google",
    label: "Google Gemini",
    authKind: "key",
    adapter: "google",
    baseUrl: "https://generativelanguage.googleapis.com",
    defaultModel: "gemini-3.5-flash",
    models: [
      "gemini-3.6-flash",
      "gemini-3.5-flash",
      "gemini-3.5-flash-lite",
      "gemini-3.1-pro-preview",
      "gemini-3.7-flash",
    ],
  },
  {
    id: "google-vertex",
    label: "Google Vertex AI",
    authKind: "key",
    adapter: "google",
    baseUrl: "https://aiplatform.googleapis.com",
    defaultModel: "gemini-3-pro",
    models: [],
  },
  {
    id: "google-antigravity",
    label: "Google Antigravity",
    authKind: "oauth",
    adapter: "google",
    baseUrl: "https://daily-cloudcode-pa.googleapis.com",
    defaultModel: "gemini-3.8-flash-high",
    models: [
      "gemini-3.8-flash-high",
      "gemini-3.7-flash-high",
      "gemini-3.6-flash-high",
      "gemini-3.5-flash-low",
      "gemini-3.5-flash-extra-low",
      "gemini-3.1-pro-low",
      "gemini-3.1-flash-lite",
      "gemini-3.1-flash-image",
      "gemini-3-flash",
      "gemini-3-flash-agent",
      "gemini-pro-agent",
      "claude-sonnet-4-6",
      "claude-opus-4-6-thinking",
      "gpt-oss-120b-medium",
    ],
  },
  {
    id: "azure-openai",
    label: "Azure OpenAI",
    authKind: "key",
    adapter: "azure-openai",
    baseUrl: "https://{resource}.openai.azure.com/openai",
    models: [],
  },
  {
    id: "ollama",
    label: "Ollama (local)",
    authKind: "local",
    adapter: "openai-chat",
    baseUrl: "http://localhost:11434/v1",
    models: [],
  },
  {
    id: "vllm",
    label: "vLLM (local)",
    authKind: "local",
    adapter: "openai-chat",
    baseUrl: "http://localhost:8000/v1",
    models: [],
  },
  {
    id: "lm-studio",
    label: "LM Studio (local)",
    authKind: "local",
    adapter: "openai-chat",
    baseUrl: "http://localhost:1234/v1",
    models: [],
  },
  {
    id: "devin",
    label: "Devin (experimental)",
    authKind: "local",
    adapter: "devin",
    baseUrl: "https://server.codeium.com",
    models: [],
    experimental: true,
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.deepseek.com",
    defaultModel: "deepseek-v4-flash",
    models: [
      "deepseek-chat",
      "deepseek-reasoner",
      "deepseek-v4-pro",
      "deepseek-v4-flash",
      "deepseek-v4-flash-vision-exp",
    ],
  },
  {
    id: "cerebras",
    label: "Cerebras",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.cerebras.ai/v1",
    defaultModel: "gpt-oss-120b",
    models: [],
  },
  {
    id: "chutes",
    label: "Chutes",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://llm.chutes.ai/v1",
    models: [],
  },
  {
    id: "deepinfra",
    label: "DeepInfra",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.deepinfra.com/v1/openai",
    models: [],
  },
  {
    id: "hyperbolic",
    label: "Hyperbolic",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.hyperbolic.xyz/v1",
    models: [],
  },
  {
    id: "nscale",
    label: "Nscale Serverless Inference",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://inference.api.nscale.com/v1",
    defaultModel: "meta-llama/Llama-3.1-8B-Instruct",
    models: ["meta-llama/Llama-3.1-8B-Instruct"],
  },
  {
    id: "vultr",
    label: "Vultr Serverless Inference",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.vultrinference.com/v1",
    defaultModel: "kimi-k2-instruct",
    models: ["kimi-k2-instruct"],
  },
  {
    id: "baseten",
    label: "Baseten Model APIs",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://inference.baseten.co/v1",
    models: [],
  },
  {
    id: "commandcode",
    label: "Command Code - API",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.commandcode.ai/provider/v1",
    defaultModel: "deepseek/deepseek-v4-flash",
    models: ["deepseek/deepseek-v4-flash"],
  },
  {
    id: "sambanova",
    label: "SambaNova Cloud",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.sambanova.ai/v1",
    models: [],
  },
  {
    id: "nebius",
    label: "Nebius Token Factory",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.tokenfactory.nebius.com/v1",
    models: [],
  },
  {
    id: "digitalocean",
    label: "DigitalOcean Serverless Inference",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://inference.do-ai.run/v1",
    models: [],
  },
  {
    id: "scaleway",
    label: "Scaleway Generative APIs",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.scaleway.ai/v1",
    models: [],
  },
  {
    id: "featherless",
    label: "Featherless AI",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.featherless.ai/v1",
    models: [],
  },
  {
    id: "novita",
    label: "Novita AI",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.novita.ai/openai/v1",
    models: [],
  },
  {
    id: "together",
    label: "Together",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.together.xyz/v1",
    models: [],
  },
  {
    id: "fireworks",
    label: "Fireworks",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    models: [],
  },
  {
    id: "firepass",
    label: "Fire Pass (Fireworks Kimi)",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.fireworks.ai/inference/v1",
    models: [],
  },
  {
    id: "moonshot",
    label: "Moonshot (Kimi API)",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.moonshot.ai/v1",
    defaultModel: "kimi-k2.7-code",
    models: ["kimi-k3", "kimi-k2.7-code", "kimi-k2.7-code-highspeed", "kimi-k2.6", "kimi-k2.5"],
  },
  {
    id: "huggingface",
    label: "Hugging Face",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://router.huggingface.co/v1",
    models: [],
  },
  {
    id: "nvidia",
    label: "NVIDIA NIM",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    models: [],
  },
  {
    id: "venice",
    label: "Venice",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.venice.ai/api/v1",
    models: [],
  },
  {
    id: "zai",
    label: "Z.AI — GLM Coding Plan",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.z.ai/api/coding/paas/v4",
    defaultModel: "glm-5.3",
    models: [
      "glm-5.3",
      "glm-5.3[1m]",
      "glm-5.3-flash",
      "glm-5.2",
      "glm-5.2[1m]",
      "glm-5.1",
      "glm-5",
      "glm-4.6",
    ],
  },
  {
    id: "zhipu-bigmodel",
    label: "Zhipu AI — BigModel",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    defaultModel: "glm-4.6",
    models: [
      "glm-4.6",
      "glm-4.7",
      "glm-4.7-flash",
      "glm-5",
      "glm-5.1",
      "glm-5.2",
      "glm-5.3",
      "glm-4.6v",
    ],
  },
  {
    id: "zhipu-bigmodel-coding",
    label: "Zhipu AI — BigModel Coding Plan",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4",
    defaultModel: "glm-5.3",
    models: [
      "glm-5.3",
      "glm-5.3[1m]",
      "glm-5.3-flash",
      "glm-5.2",
      "glm-5.2[1m]",
      "glm-5.1",
      "glm-5",
      "glm-4.6",
    ],
  },
  {
    id: "nanogpt",
    label: "NanoGPT",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://nano-gpt.com/api/v1",
    models: [],
  },
  {
    id: "synthetic",
    label: "Synthetic",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.synthetic.new/openai/v1",
    models: [],
  },
  {
    id: "siliconflow",
    label: "SiliconFlow",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.siliconflow.cn/v1",
    models: [],
  },
  {
    id: "qwen-cloud",
    label: "Qwen Cloud",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    models: [],
  },
  {
    id: "tencent-coding-plan",
    label: "Tencent Cloud Coding Plan",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.lkeap.cloud.tencent.com/coding/v3",
    defaultModel: "tc-code-latest",
    models: ["tc-code-latest", "glm-5", "kimi-k2.5", "minimax-m2.5"],
  },
  {
    id: "volcengine",
    label: "Volcengine Ark",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://ark.cn-beijing.volces.com/api/v3",
    defaultModel: "doubao-seed-2-1-pro-260628",
    models: [
      "doubao-seed-2-1-pro-260628",
      "doubao-seed-2-1-turbo-260628",
      "doubao-seed-evolving",
      "deepseek-v4-pro-260425",
      "deepseek-v4-flash-260425",
      "deepseek-v3-2-251201",
      "glm-5-2-260617",
      "glm-4-7-251222",
    ],
  },
  {
    id: "volcengine-coding-plan",
    label: "Volcengine Ark Coding Plan",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://ark.cn-beijing.volces.com/api/coding/v3",
    defaultModel: "ark-code-latest",
    models: [
      "ark-code-latest",
      "doubao-seed-2.0-code",
      "deepseek-v4-pro",
      "deepseek-v4-flash",
      "glm-5.3",
      "glm-5.3-flash",
      "glm-5.2",
      "kimi-k2.6",
      "minimax-m3",
    ],
  },
  {
    id: "volcengine-agent-plan",
    label: "Volcengine Ark Agent Plan",
    authKind: "key",
    adapter: "openai-responses",
    baseUrl: "https://ark.cn-beijing.volces.com/api/plan/v3",
    defaultModel: "deepseek-v4-pro",
    models: [
      "deepseek-v4-pro",
      "deepseek-v4-flash",
      "glm-5.3",
      "glm-5.3-flash",
      "glm-5.2",
      "kimi-k2.6",
      "minimax-m3",
      "doubao-seed-2.0-pro",
    ],
  },
  {
    id: "qianfan",
    label: "Qianfan (Baidu)",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://qianfan.baidubce.com/v2",
    models: [],
  },
  {
    id: "alibaba",
    label: "Alibaba Coding Plan",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://coding-intl.dashscope.aliyuncs.com/v1",
    models: [],
  },
  {
    id: "alibaba-token-plan",
    label: "Alibaba Token Plan (Beijing)",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    defaultModel: "qwen3.8-max",
    models: [
      "qwen3.8-max",
      "qwen3.7-max",
      "qwen3.7-plus",
      "qwen3.6-flash",
      "glm-5.3",
      "glm-5.3-flash",
      "glm-5.2",
      "deepseek-v4-pro",
    ],
  },
  {
    id: "alibaba-token-plan-intl",
    label: "Alibaba Token Plan (International)",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    defaultModel: "qwen3.7-max",
    models: [
      "qwen3.8-max",
      "qwen3.7-max",
      "qwen3.7-plus",
      "qwen3.6-plus",
      "qwen3.6-flash",
      "deepseek-v4-pro",
      "deepseek-v4-flash",
      "deepseek-v3.2",
      "kimi-k2.7-code",
      "kimi-k2.6",
      "kimi-k2.5",
      "glm-5.3",
      "glm-5.3-flash",
      "glm-5.2",
      "glm-5.1",
      "glm-5",
      "MiniMax-M2.5",
    ],
  },
  {
    id: "parallel",
    label: "Parallel",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://platform.parallel.ai",
    models: [],
  },
  {
    id: "zenmux",
    label: "ZenMux",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://zenmux.ai/api/v1",
    models: ["moonshotai/kimi-k3-free", "moonshotai/kimi-k3"],
  },
  {
    id: "litellm",
    label: "LiteLLM (self-hosted)",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "http://localhost:4000/v1",
    models: [],
    keyOptional: true,
  },
  {
    id: "ollama-cloud",
    label: "Ollama Cloud",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://ollama.com/v1",
    defaultModel: "glm-5.3",
    models: [
      "glm-5.3",
      "glm-5.3-flash",
      "glm-5.2",
      "deepseek-v4-pro",
      "qwen3-coder:480b",
      "gpt-oss:120b",
      "kimi-k2.6",
      "minimax-m3",
      "qwen3.5:397b",
      "gemma4:31b",
    ],
  },
  {
    id: "mistral",
    label: "Mistral",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.mistral.ai/v1",
    defaultModel: "codestral-latest",
    models: [],
  },
  {
    id: "minimax",
    label: "MiniMax — Coding Plan",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.minimax.io/v1",
    defaultModel: "MiniMax-M3",
    models: [
      "MiniMax-M3",
      "MiniMax-M2.7",
      "MiniMax-M2.7-highspeed",
      "MiniMax-M2.5",
      "MiniMax-M2.5-highspeed",
      "MiniMax-M2.1",
      "MiniMax-M2.1-highspeed",
      "MiniMax-M2",
    ],
  },
  {
    id: "minimax-cn",
    label: "MiniMax — Coding Plan (CN)",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.minimaxi.com/v1",
    defaultModel: "MiniMax-M3",
    models: [
      "MiniMax-M3",
      "MiniMax-M2.7",
      "MiniMax-M2.7-highspeed",
      "MiniMax-M2.5",
      "MiniMax-M2.5-highspeed",
      "MiniMax-M2.1",
      "MiniMax-M2.1-highspeed",
      "MiniMax-M2",
    ],
  },
  {
    id: "kimi-code",
    label: "Kimi (coding)",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.kimi.com/coding/v1",
    defaultModel: "kimi-k2.7-code",
    models: [
      "k3",
      "k3[1m]",
      "kimi-k2.7-code",
      "kimi-k2.7-code-highspeed",
      "kimi-k2.6",
      "kimi-k2.5",
      "kimi-for-coding",
    ],
  },
  {
    id: "opencode-zen",
    label: "opencode zen",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://opencode.ai/zen/v1",
    models: [],
  },
  {
    id: "vercel-ai-gateway",
    label: "Vercel AI Gateway",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://ai-gateway.vercel.sh/v1",
    models: [],
  },
  {
    id: "opencode-free",
    label: "OpenCode Free",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://opencode.ai/zen/v1",
    models: [],
    keyOptional: true,
    staticHeaders: {
      "User-Agent": "opencode",
      "x-opencode-client": "desktop",
    },
  },
  {
    id: "xiaomi",
    label: "Xiaomi MiMo",
    authKind: "key",
    adapter: "anthropic",
    baseUrl: "https://api.xiaomimimo.com/anthropic",
    defaultModel: "mimo-v2.5-pro",
    models: [],
  },
  {
    id: "xiaomi-mimo",
    label: "Xiaomi MiMo (OpenAI Chat)",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.xiaomimimo.com/v1",
    defaultModel: "mimo-v2.5",
    models: ["mimo-v2.5"],
  },
  {
    id: "kilo",
    label: "Kilo",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.kilo.ai/api/gateway",
    models: [],
  },
  {
    id: "mimo-free",
    label: "MiMo Free",
    authKind: "key",
    keyOptional: true,
    adapter: "mimo-free",
    baseUrl: "https://api.xiaomimimo.com/api/free-ai/openai/chat",
    defaultModel: "mimo-auto",
    models: ["mimo-auto"],
  },
  {
    id: "mimo",
    label: "Xiaomi MiMo (token plan)",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://token-plan-cn.xiaomimimo.com/v1",
    defaultModel: "mimo-v2.5-pro",
    models: ["mimo-v2.5-pro", "mimo-v2.5"],
  },
  {
    id: "cloudflare-ai-gateway",
    label: "Cloudflare AI Gateway",
    authKind: "key",
    adapter: "anthropic",
    baseUrl: "https://gateway.ai.cloudflare.com/v1/{account-id}/{gateway}/anthropic",
    models: [],
  },
  {
    id: "cloudflare-workers-ai",
    label: "Cloudflare Workers AI",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
    defaultModel: "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
    models: [
      "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
      "@cf/qwen/qwq-32b",
      "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b",
      "@cf/moonshotai/kimi-k2.7-code",
      "@cf/zai-org/glm-5.3",
      "@cf/zai-org/glm-5.3-flash",
      "@cf/zai-org/glm-5.2",
      "@cf/mistralai/mistral-small-3.1-24b-instruct",
    ],
  },
  {
    id: "github-copilot",
    label: "GitHub Copilot",
    authKind: "oauth",
    adapter: "openai-chat",
    baseUrl: "https://api.githubcopilot.com",
    defaultModel: "gpt-4o",
    models: [
      "gpt-4o",
      "gpt-4.1",
      "gpt-4.1-mini",
      "claude-sonnet-4",
      "gemini-2.5-pro",
      "gpt-5-mini",
      "gpt-5.3-codex",
      "gpt-5.4",
      "gpt-5.4-mini",
      "gpt-5.5",
      "gpt-5.6-luna",
      "gpt-5.6-sol",
      "gpt-5.6-terra",
    ],
  },
  {
    id: "gitlab-duo",
    label: "GitLab Duo",
    authKind: "key",
    adapter: "openai-chat",
    baseUrl: "https://cloud.gitlab.com/ai/v1/proxy/openai/v1",
    models: [],
  },
] as const;

export const PROVIDER_PRESETS = PROVIDER_CATALOG;
export const PROVIDER_REGISTRY = PROVIDER_CATALOG;

export const PROVIDER_CATALOG_BY_ID: Readonly<Record<string, ProviderCatalogEntry>> = Object.freeze(
  PROVIDER_CATALOG.reduce<Record<string, ProviderCatalogEntry>>((acc, entry) => {
    acc[entry.id] = entry;
    return acc;
  }, {}),
);

export const DEDICATED_ONBOARDING_PROVIDER_IDS = new Set([
  "openai",
  "anthropic",
  "google-antigravity",
  "google-vertex",
  "zai",
]);

/** Providers the account picker draws from its own onboarding list instead of the catalog. */
export const ONBOARDING_PROVIDER_GLYPHS: readonly string[] = Object.freeze([
  "claude",
  "codex",
  "antigravity",
  "cursor",
  "kiro",
  "kimi",
  "qwen",
  "github-copilot",
  "command-code",
  "vertex",
  "cline",
  "cline-pass",
  "iflow",
  "trae",
  "nous",
  "xai",
  "zcode",
  "devin",
]);

export const GENERIC_PROVIDER_OPTIONS = PROVIDER_CATALOG.filter(
  (provider) =>
    provider.id !== "cline-pass" &&
    !ONBOARDING_PROVIDER_GLYPHS.includes(provider.id) &&
    !DEDICATED_ONBOARDING_PROVIDER_IDS.has(provider.id) &&
    provider.authKind !== "oauth",
);

export const PROVIDER_PICKER_TILE_COUNT =
  ONBOARDING_PROVIDER_GLYPHS.length + GENERIC_PROVIDER_OPTIONS.length;

export const PROVIDER_PRESETS_BY_ID = PROVIDER_CATALOG_BY_ID;

export const PROVIDER_IDS: readonly string[] = Object.freeze(
  PROVIDER_CATALOG.map((entry) => entry.id),
);

export const TOTAL_PROVIDER_COUNT = PROVIDER_CATALOG.length;

/**
 * Normalized alias mapping from OpenCodex registry IDs (and other known variants)
 * to Quotio (Desktop / Quotio-rs) identifiers:
 * - openai -> codex
 * - anthropic -> claude
 * - google-antigravity -> antigravity
 * - zai / glm / zhipu-bigmodel / zhipu-bigmodel-coding -> zcode
 */
export const OPENCODEX_TO_QUOTIO_ALIASES: Readonly<Record<string, string>> = Object.freeze({
  openai: "codex",
  anthropic: "claude",
  "google-antigravity": "antigravity",
  zai: "zcode",
  glm: "zcode",
  "zhipu-bigmodel": "zcode",
  "zhipu-bigmodel-coding": "zcode",
});

/**
 * Normalized alias mapping from Quotio / common aliases back to
 * OpenCodex registry IDs:
 * - codex -> openai
 * - claude -> anthropic
 * - antigravity -> google-antigravity
 * - zcode -> zai
 * - glm -> zai
 */
export const QUOTIO_TO_OPENCODEX_ALIASES: Readonly<Record<string, string>> = Object.freeze({
  codex: "openai",
  claude: "anthropic",
  antigravity: "google-antigravity",
  zcode: "zai",
  glm: "zai",
});

/**
 * Normalizes any provider name/alias to the canonical Quotio UI / runtime provider ID:
 * - openai -> codex
 * - anthropic -> claude
 * - google-antigravity -> antigravity
 * - zai, glm, zhipu-bigmodel -> zcode
 */
export function normalizeToQuotioProviderId(idOrAlias: string): string {
  const clean = (idOrAlias || "").trim().toLowerCase();
  return OPENCODEX_TO_QUOTIO_ALIASES[clean] ?? clean;
}

/**
 * Alias of normalizeToQuotioProviderId.
 */
export const normalizeProviderAlias = normalizeToQuotioProviderId;

/**
 * Normalizes any provider name/alias to the canonical OpenCodex registry ID:
 * - codex -> openai
 * - claude -> anthropic
 * - antigravity -> google-antigravity
 * - zcode -> zai
 */
export function normalizeToOpenCodexProviderId(idOrAlias: string): string {
  const clean = (idOrAlias || "").trim().toLowerCase();
  return QUOTIO_TO_OPENCODEX_ALIASES[clean] ?? clean;
}

/**
 * Resolves a provider catalog preset given either an OpenCodex ID, Quotio ID, or known alias.
 */
export function getProviderCatalogEntry(idOrAlias: string): ProviderCatalogEntry | undefined {
  const clean = (idOrAlias || "").trim().toLowerCase();
  if (PROVIDER_CATALOG_BY_ID[clean]) {
    return PROVIDER_CATALOG_BY_ID[clean];
  }
  const ocxId = normalizeToOpenCodexProviderId(clean);
  if (PROVIDER_CATALOG_BY_ID[ocxId]) {
    return PROVIDER_CATALOG_BY_ID[ocxId];
  }
  return undefined;
}

/**
 * Alias of getProviderCatalogEntry.
 */
export const getProviderPreset = getProviderCatalogEntry;

/**
 * Checks whether a given provider identifier or alias exists in the catalog.
 */
export function isKnownProviderId(idOrAlias: string): boolean {
  return getProviderCatalogEntry(idOrAlias) !== undefined;
}
